version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: cache_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass marcelo
    restart: always
  db:
    image: jesperdj/h2
    container_name: h2-database
    ports:
    - "8082:8082"
    - "9092:9092"
    volumes:
    - h2-data:/opt/h2-data
    restart: unless-stopped

volumes:
  redis_data:
  h2-data: